### ISSUE TITLE
Create PDF Schematic

### ISSUE THREAD

**Issue by nevvkid** [neubauek/CircuitBrains#1]
Hi @neubauek , just found this - awesome project. Doing a lot with SAMD51 MCUs myself. For example: https://github.com/dadamachines/doppler
Would be nice if you could add the schematic as PDF to the repository.
Cheers, J

**Comment by neubauek** [comment]
Hello @nevvkid. Thanks for the feedback and awesome work on your FPGA stick! I do think a PDF schematic would make sense along with additional graphics and documentation on the pinout. However, I'm going through some changes in the design right now. Once I test them, I will upload the new design and will include a PDF. Leaving this issue open until then as a reminder.

**Comment by nevvkid** [comment]
@neubauek Thanks! Let me know if you want to bounce ideas for the next revision. 
And thanks for following on Twitter. 
Send you a couple of DMs. Cheers, J

**Comment by neubauek** [comment]
PDF schematic added with v1.3 update.
