### ISSUE TITLE
Arduino SAMD51 board architecture

### ISSUE THREAD

**Issue by j3nsykes** [neubauek/CircuitBrains#3]
Hello, 
What board architecture do you recommend for the SAMD51 chip on the CircuitBrain Deluxe if I want to use Arduino IDE not Circuit Python? I have tried the Adafruit Metro M4 which successfully uploads but the pin mapping differs. Do you support this or can you advise otherwise?

Thank you!

**Comment by neubauek** [comment]
Hi @j3nsykes. Apologies for the delay in getting back to you. The GitHub notification went to the wrong email address.

I'm afraid there was never enough demand for Arduino compatibility so I did not spend the time to develop and fully test an Arduino board definition for the CircuitBrains project. The CircuitBrains project remains a CircuitPython module.

If you really need Arduino, a custom board definition can be created to suit your needs. The CircuitPython board definition  for CircuitBrains deluxe is at the following locations:
https://github.com/adafruit/circuitpython/blob/main/ports/atmel-samd/boards/circuitbrains_deluxe_m4/mpconfigboard.h
https://github.com/adafruit/circuitpython/blob/main/ports/atmel-samd/boards/circuitbrains_deluxe_m4/mpconfigboard.mk
https://github.com/adafruit/circuitpython/blob/main/ports/atmel-samd/boards/circuitbrains_deluxe_m4/pins.c

The Arduino board definition for the Adafruit Metro M4 can be sourced from the following location:
https://github.com/adafruit/arduino-board-index/blob/gh-pages/package_adafruit_index.json
Version 1.7.11 for the SAMD chips is this download:
https://adafruit.github.io/arduino-board-index/boards/adafruit-samd-1.7.11.tar.bz2

Some more information on how to create custom Arduino board definitions can be found online. For example:
https://www.instructables.com/Arduino-IDE-Creating-Custom-Boards/

**Comment by j3nsykes** [comment]
That's great thank you. I'm just in the process of craeting a custom board definition for it so will use these specs. I'll add a link to my Github with it once its finished so any other users can use it in Arduino. 

One last question - Are the IO pins 5v tolerant or 3.3V (presuming 3.3V but just checking) and is the AREF 3.3V also or 5V? 

Thank you.

**Comment by neubauek** [comment]
All I/O is 3.3V. The only place you can supply 5V is through the VIN pin, which will route through the onboard regulator to power the ATSAMD51 at 3.3V. AREF is also max of 3.3V.

Regarding AREF, there was a silicon bug in the ATSAMD51 that disabled the DACs if AREF was not powered. It is the same bug mentioned on Adafruit's pages (https://learn.adafruit.com/adafruit-metro-m4-express-featuring-atsamd51?view=all). If you are fine with 3.3V AREF, you can disregard the rest of this.

The CircuitBrains Deluxe has AREF fixed at 3.3V by default. If you want to supply a different AREF voltage from off-board, you need to pull resistor R2. It is a 0 Ohm resistor. If you position the board such that AREF is in the upper right, R2 is the upper rightmost resistor. A thick chisel soldering iron tip should do the job if you don't have access to hot air. I apologize for the clunkiness of this, but it was the only way to work around a bug in the ATSAMD51 chip.

**Comment by j3nsykes** [comment]
This is incredibly useful thank you!

**Comment by j3nsykes** [comment]
An update: here are the [Arduino custom board files](https://github.com/j3nsykes/CircuitBrainDeluxeArduinoBoardFiles). 

The [JSON file link](https://raw.githubusercontent.com/j3nsykes/CircuitBrainDeluxeArduinoBoardFiles/main/package-circuitBrainDeluxe-index.json) you can add in Arduino preferences. 


Then search board/board manager. Select 'contributed' and search Circuit Brain Deluxe. I've left the other Adafruit SAMD boards in the installer files too just whilst I test then I will streamline to remove them.
